### PR TITLE
GH-8 - rxJava + web3j updated and unit tests fixed

### LINKED ISSUE #8: replace my ugly while(true) with observables
We have different issues with the way futures, async etc is being handled in eth-propeller

The idea would be to do the following:
- having a queue of transactions that need to be handled
- a consumer that takes those transactions and send them to the network
- an observer that will listen to new blocks and will check whether the transaction has been added for each of them

This means removing the while(true) completely and use Observable (we should upgrade to RxJava 2.0)

Also to take into account, the transaction consumer needs to be single threaded, or at least single threaded for a particular private key, so it can effectively do nonce calculation and never create a bad nonce

### PR DESCRIPTION
**Pull request by fforbeck**
- [x] Web3j updated to v4.1.1
 - [x] RxJava updated to 2.2.6
 - [x] Fixed breaking changes using the new Observable and Subscriber APIs
 - [x] Replaced the while(true) with Observables
 - [x] Fixed unit tests
 - [x] Converted Observables to Flowables with Buffer backpressure strategy
 - [x] Added tests to simulate concurrent transactions 

Closes #8

### CODE REVIEW

**Comment by fforbeck** [comment]
@adridadou please take a look when you get a chance.

**Comment by fforbeck** [comment]
Please don't merge that yet. I am writing some stress tests.

File: src/main/java/org/adridadou/ethereum/propeller/EthereumProxy.java [hunk 1]
```diff
@@ -222,15 +229,18 @@ private String printTypes(Object[] constructorArgs) {
...
+                .toFlowable(BackpressureStrategy.BUFFER)
                 .filter(params -> params.getReceipt().map(receipt -> Objects.equals(receipt.hash, txHash))
                         .orElse(false) && params.getStatus() == TransactionStatus.Dropped);
 
-        Observable<TransactionInfo> timeoutBlock = eventHandler.observeBlocks()
+        Flowable<TransactionInfo> timeoutBlock = eventHandler.observeBlocks()
+                .toFlowable(BackpressureStrategy.BUFFER)
                 .filter(blockParams -> blockParams.blockNumber > currentBlock + config.blockWaitLimit())
-                .map(params -> null);
+                .map(blockInfo -> new EmptyTransactionInfo());
```
Comment (fforbeck) [inline src/main/java/org/adridadou/ethereum/propeller/EthereumProxy.java]: The emitters from rxjava2 doesn't allow to map null elements anymore. So I've changed to send an empty info and then we filter that out downstream.

**Comment by fforbeck** [comment]
This is ready for review @adridadou 
I've changed from Observable to Flowable to add buffer backpressure support. It is recommend when we have larger streams that have IO and blocking ops. Besides that, minor fixes + a simple test scenario that sends concurrent transactions.
